version: "3"
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
  zmq:
    image: cagataygurturk/docker-ssh-tunnel
    volumes:
      - $HOME/.ssh:/root/ssh:ro
    environment:
      SSH_DEBUG: "-v"
      # TUNNEL_HOST: bchn-mainnet
      # REMOTE_HOST: ec2-13-251-63-215.ap-southeast-1.compute.amazonaws.com
      TUNNEL_HOST: bchn-chipnet
      REMOTE_HOST: ec2-18-138-226-25.ap-southeast-1.compute.amazonaws.com
      LOCAL_PORT: 28332
      REMOTE_PORT: 28332
  fulcrum:
    image: cagataygurturk/docker-ssh-tunnel
    volumes:
      - $HOME/.ssh:/root/ssh:ro
    environment:
      SSH_DEBUG: "-v"
      # TUNNEL_HOST: bchn-mainnet
      # REMOTE_HOST: ec2-13-251-63-215.ap-southeast-1.compute.amazonaws.com
      # LOCAL_PORT: 50001
      # REMOTE_PORT: 50001
      TUNNEL_HOST: bchn-chipnet
      REMOTE_HOST: ec2-18-138-226-25.ap-southeast-1.compute.amazonaws.com
      LOCAL_PORT: 60001
      REMOTE_PORT: 60001
  postgres:
    image: "postgres:11.1-alpine"
    volumes:
      - watchtower_dbdata:/var/lib/postgresql/data
    env_file:
      - .env_dev
    expose:
      - "5432"
  redis:
    image: "redis:alpine"
    env_file:
      - .env_dev
    command: >
      --requirepass reid_password
  backend:
    build: .
    command: [ "supervisord", "-c", "/code/supervisor/webserver.conf", "--nodaemon" ]
    ports:
      - "8000:8000"
    env_file:
      - .env_dev
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/code
      - /code/anyhedge/js/node_modules
      - ./images:/images
  adminer:
    image: adminer
    depends_on: 
      - postgres
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: $POSTGRES_DB
    ports:
      - 3000:8080
volumes:
  watchtower_dbdata:
    driver: 'local'
