version: "3.7"
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
  bchn:
    image: cagataygurturk/docker-ssh-tunnel
    volumes:
      - /root/.ssh:/root/ssh:ro
    environment:
      SSH_DEBUG: "-v"
      TUNNEL_HOST: bchn-mainnet
      REMOTE_HOST: "${BCHN_MAINNET_HOST}"
      LOCAL_PORT: 8332
      REMOTE_PORT: 8332
  zmq:
    image: cagataygurturk/docker-ssh-tunnel
    volumes:
      - /root/.ssh:/root/ssh:ro
    environment:
      SSH_DEBUG: "-v"
      TUNNEL_HOST: bchn-mainnet
      REMOTE_HOST: "${BCHN_MAINNET_HOST}"
      LOCAL_PORT: 28332
      REMOTE_PORT: 28332
  fulcrum:
    image: cagataygurturk/docker-ssh-tunnel
    volumes:
      - /root/.ssh:/root/ssh:ro
    environment:
      SSH_DEBUG: "-v"
      TUNNEL_HOST: bchn-mainnet
      REMOTE_HOST: "${BCHN_MAINNET_HOST}"
      LOCAL_PORT: 60001
      REMOTE_PORT: 60001
  web:
    container_name: watchtower_web
    build: /root/watchtower
    image: watchtower_web
    command: [ "supervisord", "-c", "/code/supervisord.conf", "--nodaemon" ]
    env_file: /root/watchtower/compose/.env_mainnet
    volumes:
      - /var/www/images:/images
      - /code/anyhedge/js/node_modules
    ports:
      - 8000:8000
      - 9000:9000
